export default {
  login: '/admin/login',
  article_list: '/article/list',
  article_top: '/article/top',
  article_delete: '/article/delete',
  article_tag: '/article/tag',
  article_add: '/article/add',
  article_info: '/article/info',
  article_update: '/article/update',
  learn_list: '/learn/list',
  learn_delete: '/learn/delete',
  learn_add: '/learn/add',
  learn_info: '/learn/info',
  learn_update: '/learn/update',
  album_list: '/album/album',
  album_delete: '/album/album/delete',
  album_group: '/album/group',
  album_group_delete: '/album/group/delete',
  think_list: '/think/list',
  think_delete: '/think/delete',
};
